spring.application.name: school_meal_menu_backend

mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:config/mybatis-config.xml

logging:
  config: classpath:config/logback-spring.xml