spring.application.name: school_meal_menu_backend

server:
  address: 0.0.0.0
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/today
    username: today
    password: today

mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:config/mybatis-config.xml

logging:
  config: classpath:config/logback-spring.xml
